imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %node_executable%
            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules, %kernel.root_dir%/../node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
            apply_to: "\.(less|css)$"
        yui_js:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
            apply_to: "\.(js)$"