imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %node_executable%
            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules, %kernel.root_dir%/../node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
            apply_to: "\.(less|css)$"
        yui_js:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
            apply_to: "\.(js)$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secured_area
  
    resource_owners:
        github:
            type:                github
            client_id:            %github_oauth_client_id%
            client_secret:       %github_oauth_client_secret%
            scope:               "user,repo,gist"
            paths:
                githubId: login
            
    # optional FOSUserBundle integration
    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30
    
        # mapping between resource owners (see below) and properties
        properties:
            github: githubId
            
    # if you want to use 'connect' and do not use the FOSUB integration, configure these separately
    connect: ~
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: RRaven\Bundle\LaughingbearBundle\Entity\User
            
buzz:
    throw_exception: true
    profiler:  %kernel.debug%
    browsers:
        default:
            client: curl
        rraven.laughingbear.github:
            client: curl
            message_factory: RRaven\Bundle\LaughingbearBundle\Utility\Buzz\Message\Factory\Factory
            host: http://www.google.com

sonata_admin:
    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout: SonataAdminBundle::standard_layout.html.twig
        ajax:   SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:  SonataAdminBundle:CRUD:show.html.twig
        edit:   SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text: ~
        sonata.block.service.action: ~
        sonata.block.service.rss: 

mopa_bootstrap:
    navbar: ~
