services:
    rraven.helper.apimap:
        class: RRaven\Bundle\LaughingbearBundle\Helper\ApiMapHelper
        arguments: ["@annotation_reader", "@logger"]
    rraven.helper.api:
        class: RRaven\Bundle\LaughingbearBundle\Helper\ApiHelper
        arguments: ["@annotation_reader", "@logger", "@rraven.buzz.github"]
    rraven.helper.menumenu:
        class: RRaven\Bundle\LaughingbearBundle\Helper\MenuMenuHelper
        arguments: ["@annotation_reader", "@logger", "@router", "@security.access.method_interceptor"]
    rraven.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @rraven.navbar_main_menu=, rightmenu: @rraven.navbar_right_menu= }
            - {}
            - { title: "Laughing Bear", titleRoute: "rraven_laughingbear_default_index", fixedTop: true, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    rraven.navbar_menu_builder:
        class: RRaven\Bundle\LaughingbearBundle\Menu\NavbarMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context' ]

    rraven.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory_service: rraven.navbar_menu_builder
        factory_method: createMainMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    rraven.navbar_right_menu:
        class: Knp\Menu\MenuItem
        factory_service: rraven.navbar_menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    rraven.buzz.github.messagefactory:
        class: RRaven\Bundle\LaughingbearBundle\Utility\Buzz\Message\Factory\Factory
        public: false
        
    rraven.buzz.default.client:
        class: Buzz\Client\Curl
        tags:
            -  { name: buzz.client }

    rraven.buzz.github:        
        class: Buzz\Browser
        arguments: ["@rraven.buzz.default.client", "@rraven.buzz.github.messagefactory"]
        
    rraven.laughingbear.auto_flush:
        class: RRaven\Bundle\LaughingbearBundle\EventListener\AutoFlush
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            